FROM       ubuntu:16.04
MAINTAINER Sriramajeyam Sugumaran "https://github.com/yesoreyeram"

RUN apt-get update

RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd

RUN echo 'root:root' |chpasswd

RUN apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*

RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

EXPOSE 22

CMD    ["/usr/sbin/sshd", "-D"] 
